#!/bin/bash
# Bash is always the first command in the script

# Description: System Report script to automate and valuable information
# All data is labeled and organized for human consumption

# Firewall status needs super-user to execute

# Assignment 1: System Report Script




# Variables

# hostnamectl to find where OS is located, piped into grep to find "Operating", piped into awk to print 3rd, 4th, 5th word on line
OS=$(hostnamectl | grep "Operating" | awk '{print$3,$4,$5}')

# Used hostname to display host, whoami to display username and date command (%A - Day name, %b - Month, %-d - day of month without 0, %Y - Year)
date=$(date +"%A, %b %-d, %Y at %r")

# Made uptime look pretty and used awk to only show what I desire
uptimepretty=$(uptime -p | awk '{print$2,$3,$4,$5}')

# CPU make and model using lscpu to see cpu info, grep to grab the model location and awk to provide information. Used sed to remove leading spaces.
# ^ finds the beginning, [ \t] match any character inside (space or tab), * is used to tell sed to go until a letter. / replaces it with nothing.
cpu=$(lscpu | grep "Model name" | awk -F: '{print$2}' | sed 's/^[ \t]*//')

# Uses grep to pull the total memory installed from /proc/meminfo, uses awk to print size of memory then divide it by 1024 twice to convert from KBs to GBs
# printf fills in the blanks and %.0f pulls the placeholder and rounds number to look cleaner
ramsize=$(grep "MemTotal" /proc/meminfo | awk '{printf "%.0f GB", $2/1024/1024}')

# Display installed disks, pull specific drives with "nvme" in the name with grep, cleaned up desired output with awk (drive, model, size) with | seperating each
disks=$(df -h / | awk '{print $1,$4}')

# inxi -G to find graphics, locate line with device with grap, print 4 words with awk for desired outcome
videocard=$(inxi -G | grep "Device" | awk '{print $2,$3,$4,$5}')

# Finds default gateway, grep to pull a single line, awk to print the host address attached
hostaddress=$(ip r | grep "default" | awk '{print $9}')

# Finds default gateway, greps to pull a single line, awk to print gateway ip address
gatewayip=$(ip route show | grep "default" | awk '{print $3}')

# Uses resolvectl to find DNS information, grep to pull DNS server line we are searching for, prints IP.
dnsserverip=$(resolvectl | grep "DNS Servers" | awk '{print $3}')

# Finds user list, awk in #1 position to find only the users and soft with -u to have unique users
usersloggedin=$(who | awk '{print $1}' | sort -u)

# - new line to start so it looks cleaner -
#Finds local disks, only want target and avail output (as put output of df command and what we are searching for)
# removes headers
diskspace=$(df -h --local --output=target,avail | tail -n +2)

# Finds all processes and counts (excluding super-user privilages) and removes those pesky headers
processcount=$(ps -e --no-headers | wc -l)

# Locate load avarages within uptime, use awk -F to always have load average position and execute
loadavg=$(uptime | awk -F'load average: ' '{print $2}')

# ss to display socket info, -tuln to show network sockets desired, awk to print, remove header with NR>1
listeningports=$(ss -tuln | awk 'NR>1 {print $5}' | cut -d: -f2 | sort -nu | paste -sd,)

# Needs super-user to show firewall status
ufwstatus=$(ufw status)

# EXECUTE SCRIPT

cat << EOF

System Report for $(hostname) generated by $(whoami), on $date

System Information
-----------------
OS: $OS
Uptime: $uptimepretty
CPU: $cpu
RAM: $ramsize
Disk\(s\): $disks
Video: $videocard
Host Address: $hostaddress
Gateway IP: $gatewayip
DNS Server: $dnsserverip
 
System Status
------------
Users Logged In: $usersloggedin
Disk Space: 
$diskspace
Process Count: $processcount
Load Averages: $loadavg
Listening Network Ports: $listeningports
UFW Status: $ufwstatus

EOF




